sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
cache: yarn
before_install:
  # - docker build -t weeznog/docker-react-now -f ./client/Dockerfile.dev ./client
  - yarn add now
script:
  - echo "skipping tests"
  # - docker run weeznog/docker-react-now yarn test -- --coverage
deploy:
  - provider: script
    script: bash deploy-stage.sh
    skip_cleanup: true
    on:
      branch: stage
      # all_branches: true
      # master: false
  - provider: script
    script: bash deploy-prod.sh
    skip_cleanup: true
    on:
      branch: master
notifications:
  # slack:
  # look at travis docs for travis - might be better to add to env rather then cli
  # secure: ARQ+W7URBmpH5GnTUVhavPuYqxA5g/80jwoj9c+qB9jb87u/WhfY9oO90S+SRPVKRNXl8U6iuEXuFYjYPSUzZyimJS7SsY8g+FzgO6I+rJoPo638O6EL7fHB6epGH7T90ycyE3A7+akwkuBnPmoFWEr4xI2tVkNGQQ30h9QnQjf9S0TPH7w45pw4zZMHDS2R7Ga/LyYlVuUgxheN+wXhCvL0y96Lg4HxykJtJgts6UPprUNWUp/YvFXdVOftXfqtS8C2q7j6mMOjLYj59AqOtUJu8QuTIFyM2vh1jq4lwpQg6dosntLeSLeqhB6RCBy4n4N0y+tYEK8VCXb/y5umMIvndoz5o1KVr2limr0UVwISEeOebjR3nsUwVi8GVrBshBn4uPTbDV4T1Ug+KVISiyDFB8SEaMwFfFnBxoC1ogZMeZLI+9eAzAk7RbMfaEl2HVdV7BbztK8cMo1yzm5dmPG0lyE6+U30DRB24L6LeQPt075DX3CFXxxQAxliTstTuSqrgTkWiaWrQYGcxe5I/ImSZJwoucGicRgY811QoNANerwhCbcYpoKoEae3j3Dci8TAuchQZX2uugo68YSYPeIzKgaEwlxd3WeVsmWlUfcyFGnl827CMaRnMMYPKA7jDsdIps3myV2TOGUk/L2QWD0M8+VI3dOy3QQ+UC1Yqtg=
  email: false
