sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
cache: yarn
before_install:
  # - docker build -t weeznog/docker-react-now -f ./client/Dockerfile.dev ./client
  - yarn add now
script:
  - echo "skipping tests"
  # - docker run weeznog/docker-react-now yarn test -- --coverage
deploy:
  - provider: script
    script: bash deploy-stage.sh
    skip_cleanup: true
    on:
      branch: stage
      # all_branches: true
      # master: false
  - provider: script
    script: bash deploy-prod.sh
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
