sudo: required
services:
  - docker

# before_install:
#   - docker build -t weeznog/docker-react-now -f Dockerfile.dev .
# script:
#   - docker run weeznog/docker-react-now yarn test -- --coverage

deploy:
  # - provider: script # Run a custom deployment script which we will define below
  #   script: now --docker --public --token $NOW_TOKEN
  #   skip_cleanup: true
  #   on:
  #     all_branches: true
  #     master: false
  - provider: script
    # script: now --docker --public --token $NOW_TOKEN && now alias drew-test --token $NOW_TOKEN
    script: now --docker --public --token JZN60E4PDTERfoGXGMeQEcMI
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
